### ISSUE TITLE
[cetic/adminer] Add ingressClassName field to ingress manifest

### ISSUE THREAD

**Issue by mknapcok** [cetic/helm-adminer#11]
**Is your feature request related to a problem? Please describe.**
Yes. From kubernetes 1.22 the _kubernetes.io/ingress.class: nginx_ annotation will be deprecated. Should be using field spec.ingressClassName. We would like to implement it already.

**Describe the solution you'd like**
Add ingressClassName to ingress spec field. It's been added to kubernetes 1.18
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
```

**Describe alternatives you've considered**

**Additional context**

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

Specifying the Class of an Ingress
```

A new ingressClassName field has been added to the Ingress spec that is used to reference the IngressClass that should be used to implement this Ingress.

Deprecating the Ingress Class Annotation

Before the IngressClass resource was added in Kubernetes 1.18, a similar concept of Ingress class was often specified with a kubernetes.io/ingress.class annotation on the Ingress. Although this annotation was never formally defined, it was widely supported by Ingress controllers, and should now be considered formally deprecated.
```
